### ISSUE TITLE
Proposal for degreeOfEstablishment term + Blackburn et al. 2011 vocab

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/vocab#4]
_Note: summary of discussion at TrIAS vocab discussion on 2018-03-28_

## Vocab

category | definition | human readable label
--- | --- | ---
A | Not transported beyond limits of native range | native
B1 | Individuals transported beyond limits of native range, and in captivity or quarantine (i.e. individuals provided with conditions suitable for them, but explicit measures of containment are in place) | captive
B2 | Individuals transported beyond limits of native range, and in cultivation (i.e. individuals provided with conditions suitable for them but explicit measures to prevent dispersal are limited at best) | cultivated
B3 | Individuals transported beyond limits of native range, and directly released into novel environment | transported
C0 | Individuals released into the wild (i.e. outside of captivity or cultivation) in location where introduced, but incapable of surviving for a significant period | released
C1 | Individuals surviving in the wild (i.e. outside of captivity or cultivation) in location where introduced, no reproduction | casual
C2 | Individuals surviving in the wild in location where introduced, reproduction occurring, but population not self-sustaining | reproducing
C3 | Individuals surviving in the wild in location where introduced, reproduction occurring, and population self-sustaining | established
D1 | Self-sustaining population in the wild, with individuals surviving a significant distance from the original point of introduction | dispersed
D2 | Self-sustaining population in the wild, with individuals surviving and reproducing a significant distance from the original point of introduction | colonizing
E | Fully invasive species, with individuals dispersing, surviving and reproducing at multiple sites across a greater or lesser spectrum of habitats and extent of occurrence | invasive

## Todo

* [ ] Make the case for a new term `degreeOfEstablishment` (alternative name we decided not to use is `invasionStage`)
* [ ] This term should be part of the `distribution` extension. Could be argued as a property of a occurrence too.
* [ ] Term expresses information for how established a species is: `native` (in original habitat), `captive`, `casual` (in new habitat), `naturalised/established`, `invasive`.
* [ ] This information is expressed in the unified framework for biological invasions ([Blackburn et al 2011](http://doc.rero.ch/record/24725/files/bach_puf.pdf), but that vocab needs to be formatted as a proper vocab.
* [ ] We'll have to think what to use as term labels. Blackburn et al uses obscure labels `A`, `B1`. We could translate those in human readable ones `native`, `casual`, but it will be hard to do for all. Might be better to write good definitions (cf. [threatStatus](http://rs.gbif.org/vocabulary/iucn/threat_status.xml))
